version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_queue_project
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: queue_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: pgdata
